# Generated by Django 5.2.9 on 2025-12-11 21:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_passwordresetcode"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FollowRelationship",
        ),
    ]
