"""
Django settings for config project.
Generated by 'django-admin startproject'.
"""

from pathlib import Path

# ----------------------------------------------------
# Base
# ----------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-a!s5i*gh%b#pbu0&!=zsh0lz4064=7t9*8xmk1&c8nh@ma1$v6"

DEBUG = True
ALLOWED_HOSTS = ["*"]


# ----------------------------------------------------
# Applications
# ----------------------------------------------------
INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",

    # Local apps
    "users.apps.UsersConfig",
    "core.apps.CoreConfig",
    "films.apps.FilmsConfig",
]

# Note: Using Django's built-in User model (not a custom one)
# AUTH_USER_MODEL = "users.User"  # Removed - no custom User model exists


# ----------------------------------------------------
# Middleware
# ----------------------------------------------------
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ----------------------------------------------------
# URLs / WSGI
# ----------------------------------------------------
ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ----------------------------------------------------
# Database (LOCAL DEV – SQLite)
# ----------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# ----------------------------------------------------
# Password validation
# ----------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ----------------------------------------------------
# Internationalization
# ----------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# ----------------------------------------------------
# Static files
# ----------------------------------------------------
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ----------------------------------------------------
# Django REST Framework
# ----------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
}


# ----------------------------------------------------
# CORS
# ----------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True


# ----------------------------------------------------
# External APIs
# ----------------------------------------------------

# DeepSeek
DEEPSEEK_API_KEY = ""
DEEPSEEK_MODEL = "deepseek-chat"

# IMDb API
IMDBAPI_BASE = "https://api.imdbapi.dev"

# KinoCheck API
KINO_BASE = "https://api.kinocheck.com"
KINO_API_KEY = "fCxG8kroiDIHzQZWXnhJ0NVdqwqtmahDz0OSnCieTMEwTlj6vj37Bs4KFbcaYmlv"


# Watchmode
WATCHMODE_BASE = "https://api.watchmode.com"
WATCHMODE_API_KEY = ""


# ----------------------------------------------------
# HTTP Client Defaults
# ----------------------------------------------------
HTTP_TIMEOUT = 30
HTTP_RETRIES = 3
