from django.urls import path
from .views import (
    SearchView,
    AdminBadgeStatsView,
    AdminFilmCreateView,
    AdminFilmDeleteView,
    AdminFilmsView,
    AdminFilmUpdateView,
    AdminFlaggedCommentsView,
    AdminLogsView,
    AdminModerateCommentView,
    AdminMoodStatsView,
    AdminRecentReviewsView,
    AdminStatsView,
    AdminUserActivityView,
    AdminUserBanView,
    AdminUserDeleteView,
    AdminUsersView,
    AwardBadgeView,
    BadgeListView,
    BadgeProgressView,
    CheckFilmWatchedView,
    CheckFollowStatusView,
    CreateCustomBadgeView,
    FilmAKAsView,
    FilmAwardNominationsView,
    FilmBoxOfficeView,
    FilmCertificatesView,
    FilmCompanyCreditsView,
    FilmCreditsView,
    FilmDetailView,
    FilmEpisodesView,
    FilmImagesView,
    FilmMoodView,
    FilmParentsGuideView,
    FilmRatingView,
    FilmRatingsListView,
    FilmReleaseDatesView,
    FilmReviewsListView,
    FilmSearchGraphQLView,
    FilmSeasonsView,
    FilmStreamingView,
    FilmTrailerView,
    FilmVideosView,
    FlagCommentView,
    FollowUserView,
    KinoCheckLatestTrailersView,
    KinoCheckMovieByIdView,
    KinoCheckTrendingTrailersView,
    KinoCheckTrailersByGenreView,
    ListAddFilmView,
    ListCreateView,
    ListDetailView,
    ListListView,
    ListRemoveFilmView,
    MarkFilmUnwatchedView,
    MarkFilmWatchedView,
    RecommendationsView,
    ReviewCreateView,
    ReviewDetailView,
    ReviewLikeView,
    TopLikedReviewsView,
    UnflagCommentView,
    UserBadgesView,
    UserFollowersView,
    UserFollowingView,
    UserListsView,
    UserRatingsListView,
    UserReviewsView,
    UserWatchedFilmsView,
)

urlpatterns = [
    path("search/imdb/", SearchView.as_view(), name="search-imdb"),
    path("films/<str:imdb_id>", FilmDetailView.as_view(), name="film-detail"),
    path("films/<str:imdb_id>/trailer", FilmTrailerView.as_view(), name="film-trailer"),
    path("films/<str:imdb_id>/streaming", FilmStreamingView.as_view(), name="film-streaming"),
    path("films/<str:imdb_id>/rate", FilmRatingView.as_view(), name="film-rate"),
    path("films/<str:imdb_id>/ratings", FilmRatingsListView.as_view(), name="film-ratings-list"),
    path("films/<str:imdb_id>/mood", FilmMoodView.as_view(), name="film-mood"),
    path("films/<str:imdb_id>/watched", MarkFilmWatchedView.as_view(), name="film-mark-watched"),
    path("films/<str:imdb_id>/unwatched", MarkFilmUnwatchedView.as_view(), name="film-mark-unwatched"),
    path("films/<str:imdb_id>/watched-status", CheckFilmWatchedView.as_view(), name="film-watched-status"),
    path("films/<str:imdb_id>/reviews", FilmReviewsListView.as_view(), name="film-reviews-list"),
    path("films/<str:imdb_id>/reviews/create", ReviewCreateView.as_view(), name="film-review-create"),
    path("recommendations/", RecommendationsView.as_view(), name="recommendations"),
    path("lists/", ListListView.as_view(), name="list-list"),
    path("lists/create/", ListCreateView.as_view(), name="list-create"),
    path("lists/<int:list_id>", ListDetailView.as_view(), name="list-detail"),
    path("lists/<int:list_id>/films", ListAddFilmView.as_view(), name="list-add-film"),
    path("lists/<int:list_id>/films/<str:imdb_id>", ListRemoveFilmView.as_view(), name="list-remove-film"),
    path("reviews/<int:review_id>", ReviewDetailView.as_view(), name="review-detail"),
    path("reviews/<int:review_id>/like", ReviewLikeView.as_view(), name="review-like"),
    path("reviews/top-liked", TopLikedReviewsView.as_view(), name="top-liked-reviews"),
    path("films/<str:imdb_id>/credits", FilmCreditsView.as_view(), name="film-credits"),
    path("films/<str:imdb_id>/release-dates", FilmReleaseDatesView.as_view(), name="film-release-dates"),
    path("films/<str:imdb_id>/akas", FilmAKAsView.as_view(), name="film-akas"),
    path("films/<str:imdb_id>/seasons", FilmSeasonsView.as_view(), name="film-seasons"),
    path("films/<str:imdb_id>/episodes", FilmEpisodesView.as_view(), name="film-episodes"),
    path("films/<str:imdb_id>/images", FilmImagesView.as_view(), name="film-images"),
    path("films/<str:imdb_id>/videos", FilmVideosView.as_view(), name="film-videos"),
    path("films/<str:imdb_id>/award-nominations", FilmAwardNominationsView.as_view(), name="film-award-nominations"),
    path("films/<str:imdb_id>/parents-guide", FilmParentsGuideView.as_view(), name="film-parents-guide"),
    path("films/<str:imdb_id>/certificates", FilmCertificatesView.as_view(), name="film-certificates"),
    path("films/<str:imdb_id>/company-credits", FilmCompanyCreditsView.as_view(), name="film-company-credits"),
    path("films/<str:imdb_id>/box-office", FilmBoxOfficeView.as_view(), name="film-box-office"),
    path("search/graphql", FilmSearchGraphQLView.as_view(), name="search-graphql"),
    path("kinocheck/trailers/latest", KinoCheckLatestTrailersView.as_view(), name="kinocheck-latest-trailers"),
    path("kinocheck/trailers/trending", KinoCheckTrendingTrailersView.as_view(), name="kinocheck-trending-trailers"),
    path("kinocheck/trailers/", KinoCheckTrailersByGenreView.as_view(), name="kinocheck-trailers-by-genre"),
    path("kinocheck/movies", KinoCheckMovieByIdView.as_view(), name="kinocheck-movie-by-id"),
    path("users/<str:username>/follow", FollowUserView.as_view(), name="follow-user"),
    path("users/<str:username>/followers", UserFollowersView.as_view(), name="user-followers"),
    path("users/<str:username>/following", UserFollowingView.as_view(), name="user-following"),
    path("users/<str:username>/follow-status", CheckFollowStatusView.as_view(), name="check-follow-status"),
    path("badges/", BadgeListView.as_view(), name="badge-list"),
    path("badges/progress", BadgeProgressView.as_view(), name="badge-progress"),
    path("badges/create", CreateCustomBadgeView.as_view(), name="create-custom-badge"),
    path("badges/award", AwardBadgeView.as_view(), name="award-badge"),
    path("users/<str:username>/badges", UserBadgesView.as_view(), name="user-badges"),
    path("users/<str:username>/watched", UserWatchedFilmsView.as_view(), name="user-watched-films"),
    path("reviews/<int:review_id>/flag", FlagCommentView.as_view(), name="flag-comment"),
    path("reviews/<int:review_id>/unflag", UnflagCommentView.as_view(), name="unflag-comment"),
    path("admin/reviews/<int:review_id>/moderate", AdminModerateCommentView.as_view(), name="admin-moderate-comment"),
    path("admin/reviews/flagged", AdminFlaggedCommentsView.as_view(), name="admin-flagged-comments"),
    # Admin dashboard endpoints
    path("admin/stats/", AdminStatsView.as_view(), name="admin-stats"),
    path("admin/users/", AdminUsersView.as_view(), name="admin-users"),
    path("admin/users/<int:user_id>/ban", AdminUserBanView.as_view(), name="admin-user-ban"),
    path("admin/users/<int:user_id>/delete", AdminUserDeleteView.as_view(), name="admin-user-delete"),
    path("admin/users/<int:user_id>/activity", AdminUserActivityView.as_view(), name="admin-user-activity"),
    path("admin/films/", AdminFilmsView.as_view(), name="admin-films"),
    path("admin/films/create", AdminFilmCreateView.as_view(), name="admin-film-create"),
    path("admin/films/<str:film_id>/update", AdminFilmUpdateView.as_view(), name="admin-film-update"),
    path("admin/films/<str:film_id>/delete", AdminFilmDeleteView.as_view(), name="admin-film-delete"),
    path("admin/badges/stats", AdminBadgeStatsView.as_view(), name="admin-badge-stats"),
    path("admin/moods/stats", AdminMoodStatsView.as_view(), name="admin-mood-stats"),
    path("admin/logs", AdminLogsView.as_view(), name="admin-logs"),
    path("admin/reviews/recent", AdminRecentReviewsView.as_view(), name="admin-reviews-recent"),
]