# Generated by Django 5.1.3 on 2025-12-02 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('poster_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('full_json', models.JSONField(blank=True, null=True)),
                ('cached_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['imdb_id'], name='films_film_imdb_id_e57888_idx'), models.Index(fields=['title'], name='films_film_title_72d7db_idx')],
            },
        ),
    ]
