# Generated by Django 5.1.3 on 2025-12-04 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_before', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('excited', 'Excited'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('bored', 'Bored'), ('energetic', 'Energetic'), ('relaxed', 'Relaxed'), ('stressed', 'Stressed'), ('neutral', 'Neutral')], help_text='Emotional state before watching the film', max_length=20)),
                ('mood_after', models.CharField(blank=True, choices=[('happy', 'Happy'), ('sad', 'Sad'), ('excited', 'Excited'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('bored', 'Bored'), ('energetic', 'Energetic'), ('relaxed', 'Relaxed'), ('stressed', 'Stressed'), ('neutral', 'Neutral')], help_text='Emotional state after watching the film', max_length=20, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', 'film'], name='films_mood_user_id_576099_idx'), models.Index(fields=['film'], name='films_mood_film_id_4d2912_idx')],
                'unique_together': {('user', 'film')},
            },
        ),
    ]
