# Generated by Django 5.1.3 on 2025-12-06 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_list_listitem_review_reviewlike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_auto_detected_spoiler',
            field=models.BooleanField(default=False, help_text='Whether the system automatically detected this as a spoiler (FR06.2)'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_spoiler',
            field=models.BooleanField(default=False, help_text='Whether the user manually marked this as a spoiler (FR06.1)'),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('criteria_type', models.CharField(choices=[('films_watched', 'Films Watched'), ('reviews_written', 'Reviews Written'), ('lists_created', 'Lists Created'), ('ratings_given', 'Ratings Given'), ('followers_count', 'Followers Count'), ('custom', 'Custom Challenge')], help_text='Type of criteria for earning this badge (FR05.1)', max_length=50)),
                ('criteria_value', models.IntegerField(help_text='Value needed to earn this badge (e.g., 10 films watched)')),
                ('icon_url', models.URLField(blank=True, help_text='URL to badge icon/image', max_length=2000, null=True)),
                ('is_custom', models.BooleanField(default=False, help_text='Whether this is a user-created custom badge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this badge (for custom badges)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.IntegerField(default=0, help_text='Current progress towards badge (for tracking)')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='films.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['criteria_type'], name='films_badge_criteri_fa1880_idx'),
        ),
        migrations.AddIndex(
            model_name='badge',
            index=models.Index(fields=['is_custom'], name='films_badge_is_cust_33d8b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['user', 'earned_at'], name='films_userb_user_id_3ede2a_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadge',
            index=models.Index(fields=['badge'], name='films_userb_badge_i_69c7bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together={('user', 'badge')},
        ),
    ]
