# Generated by Django 5.1.3 on 2025-12-06 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_review_is_auto_detected_spoiler_review_is_spoiler_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True, help_text='When the user marked the film as watched')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_users', to='films.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_films', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_at'],
                'indexes': [models.Index(fields=['user', 'watched_at'], name='films_watch_user_id_ceee68_idx'), models.Index(fields=['film'], name='films_watch_film_id_447ae8_idx')],
                'unique_together': {('user', 'film')},
            },
        ),
    ]
