# Generated by Django 5.1.3 on 2025-12-06 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_watchedfilm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Inappropriate Content'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('other', 'Other')], default='other', help_text='Reason for flagging the comment', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about why this comment was flagged', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='review',
            name='flagged_count',
            field=models.IntegerField(default=0, help_text='Number of times this comment has been flagged by users'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='When this comment was moderated by admin', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Admin user who moderated this comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text='Reason for moderation decision (e.g., blacklisted words detected)', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Moderation status: pending, approved, or rejected', max_length=20),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['moderation_status'], name='films_revie_moderat_cd58cd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['flagged_count'], name='films_revie_flagged_1e357a_idx'),
        ),
        migrations.AddField(
            model_name='commentflag',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='films.review'),
        ),
        migrations.AddField(
            model_name='commentflag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='commentflag',
            index=models.Index(fields=['review'], name='films_comme_review__368561_idx'),
        ),
        migrations.AddIndex(
            model_name='commentflag',
            index=models.Index(fields=['created_at'], name='films_comme_created_c6f514_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentflag',
            unique_together={('user', 'review')},
        ),
    ]
