# Generated by Django 5.1.3 on 2025-12-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
