# Generated by Django 5.1.3 on 2025-12-22 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_delete_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('input', 'Input (user message)'), ('output', 'Output (assistant answer)')], max_length=10)),
                ('allow', models.BooleanField(default=False)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['direction'], name='films_moder_directi_39aa40_idx'), models.Index(fields=['allow'], name='films_moder_allow_eb18f9_idx'), models.Index(fields=['created_at'], name='films_moder_created_0caf6f_idx')],
            },
        ),
    ]
