# Generated by Django 5.1.3 on 2025-12-22 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_moderationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('blocked', models.BooleanField(default=False)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='films_recom_user_id_0dcaa0_idx'), models.Index(fields=['blocked'], name='films_recom_blocked_94a18f_idx')],
            },
        ),
    ]
