# Generated by Django 5.1.3 on 2025-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_recommendationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='direction',
            field=models.CharField(choices=[('in', 'Input (user message)'), ('out', 'Output (assistant answer)')], max_length=10),
        ),
    ]
