# Generated by Django 5.1.3 on 2025-12-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetCode',
        ),
    ]
