# Generated by Django 5.1.3 on 2025-12-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_passwordresetcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
